name: docker tests

on:
  push:
    branches:
      - 3.1_ds
  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Start and init the oauth server
      run: ./ci/init_hydra_oauth_server.sh
      timeout-minutes: 5

    - name: Build with Maven skipTests
      run: mvn clean checkstyle:check install -ntp -B -DskipTests

    - name: tests module
      run: mvn test -ntp -B -DfailIfNoTests=false '-Dtest=DockerTest' -pl tests
      timeout-minutes: 120

    - name: package surefire artifacts
      if: failure()
      run: |
        rm -rf artifacts
        mkdir artifacts
        find . -type d -name "*surefire*" -exec cp --parents -R {} artifacts/ \;
        zip -r artifacts.zip artifacts

    - uses: actions/upload-artifact@master
      name: upload surefire-artifacts
      if: failure()
      with:
        name: surefire-artifacts
        path: artifacts.zip
